server:
  port: 8080
  servlet:
    context-path: /

spring:
  devtools:
    livereload:
      enabled: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/statistc?useUnicode=true&characterEncoding=utf-8
    username: root
    password: eodend101
